spring:
  application:
    name: springboot-dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/day15?serverTimezone=UTC
server:
  port: 80
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml